NUTRIENT_CATEGORIES = {
    "Protein (g)" : "macronutrients",
    "Carbohydrate (g)" : "macronutrients",
    "Fat, total (g)" : "macronutrients",
    "Alcohol (g)" : "macronutrients",
    "Vitamin A as retinol activity equivalents (μg)" : "vitamins",
    "Retinol (μg)" : "vitamins",
    "Carotene, alpha (μg)" : "vitamins",
    "Carotene, beta (μg)" : "vitamins",
    "Cryptoxanthin, beta (μg)" : "vitamins",
    "Lycopene (μg)" : "vitamins",
    "Lutein + zeaxanthin (μg)": "vitamins",
    "Vitamin E as alpha-tocopherol (mg)" : "vitamins",
    "Added vitamin E (mg)" : "vitamins",
    "Vitamin D (μg)" : "vitamins",
    "Vitamin K as phylloquinone (μg)" : "vitamins",
    "Vitamin C (mg)" : "vitamins",
    "Thiamin (mg)" : "vitamins",
    "Riboflavin (mg)" : "vitamins",
    "Niacin (mg)" : "vitamins",
    "Vitamin B-6 (mg)" : "vitamins",
    "Folate, total (μg)" : "vitamins",
    "Folate as dietary folate equivalents (μg)" : "vitamins",
    "Folic acid (μg)" : "vitamins",
    "Food folate (μg)" : "vitamins",
    "Vitamin B-12 (μg)" : "vitamins",
    "Added vitamin B-12 (μg)": "vitamins",
    "Calcium (mg)" : "minerals",
    "Iron (mg)" : "minerals",
    "Magnesium (mg)" : "minerals",
    "Phosphorus (mg)" : "minerals",
    "Potassium (mg)" : "minerals",
    "Sodium (mg)" : "minerals",
    "Zinc (mg)" : "minerals",
    "Copper (mg)" : "minerals",
    "Selenium (μg)" : "minerals",
 }