# Generated by Django 4.2.5 on 2024-04-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WFPB_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="body",
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.FileField(blank=True, upload_to="img/"),
        ),
    ]
