# Generated by Django 5.0.4 on 2024-04-11 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WFPB_app", "0007_season_remove_seasonal_season_seasonal_seasons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seasonal",
            old_name="seasons",
            new_name="season",
        ),
    ]
