# Generated by Django 5.0.4 on 2024-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WFPB_app", "0008_rename_seasons_seasonal_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonal",
            name="season",
            field=models.ManyToManyField(
                related_name="seasonals", to="WFPB_app.season"
            ),
        ),
    ]
