# Generated by Django 5.0.4 on 2024-05-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WFPB_app", "0009_alter_seasonal_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("body", models.TextField(default=True)),
                ("link", models.URLField(blank=True, max_length=128, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="static/img"),
                ),
            ],
        ),
    ]
