# Generated by Django 5.0.4 on 2024-05-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WFPB_app", "0010_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
