# Generated by Django 5.0.4 on 2024-06-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WFPB_app", "0011_alter_resources_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
